# Generated by Django 4.2 on 2023-04-07 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import my_store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=25)),
                ('my_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PrductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryTitle', models.CharField(max_length=20)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('available', models.BooleanField()),
                ('item_count', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('price_per', models.CharField(default='kg', max_length=50)),
                ('last_Updated', models.DateTimeField(auto_now=True)),
                ('item_thresh', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(default=0.1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_category', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='my_store.prductcategory')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['product_category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(default=my_store.models.Request.get_uuid, max_length=25, null=True, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('address', models.TextField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('add_message', models.TextField(blank=True, null=True)),
                ('time_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_store.products')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_store.request')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(default=my_store.models.Orders.get_uuid, max_length=25, null=True, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('address', models.TextField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('add_message', models.TextField(blank=True, null=True)),
                ('time_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_store.products')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_store.orders')),
            ],
        ),
    ]
