# Generated by Django 3.0.8 on 2020-08-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price_per',
            field=models.CharField(default='kg', max_length=50),
        ),
    ]
