# Generated by Django 3.0.8 on 2020-08-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0002_auto_20200809_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(default='Seafood', max_length=100),
        ),
    ]
