# Generated by Django 3.0.8 on 2020-08-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0003_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('1', 'Seafood'), ('2', 'Vegetable'), ('3', 'Fruits'), ('4', 'Meat')], default='Seafood', max_length=100),
        ),
    ]
