# Generated by Django 3.0.8 on 2020-08-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0004_auto_20200809_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='is_SoldOut',
            new_name='available',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('Seafood', 'Seafood'), ('Vegetable', 'Vegetable'), ('Fruits', 'Fruits'), ('Meat', 'Meat')], default='Seafood', max_length=100),
        ),
    ]
