# Generated by Django 3.0.8 on 2020-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0005_auto_20200809_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Meat', 'Meat'), ('Seafood', 'Seafood'), ('Vegetable', 'Vegetable')], default='Seafood', max_length=100),
        ),
    ]
