# Generated by Django 3.0.8 on 2020-08-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0006_auto_20200811_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['product_category', 'title']},
        ),
    ]
