# Generated by Django 3.0.8 on 2020-08-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0007_auto_20200812_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apple', models.BooleanField()),
                ('Atis', models.BooleanField()),
                ('Grapes', models.BooleanField()),
                ('Guyabano', models.BooleanField()),
                ('Lakatan', models.BooleanField()),
                ('Lemon', models.BooleanField()),
                ('Manga', models.BooleanField()),
                ('Peras', models.BooleanField()),
                ('Saba', models.BooleanField()),
                ('Alimasag', models.BooleanField()),
                ('Alumahan', models.BooleanField()),
                ('Bangus', models.BooleanField()),
                ('Bisugo', models.BooleanField()),
                ('Galunggong', models.BooleanField()),
                ('Hipon', models.BooleanField()),
                ('Labahita', models.BooleanField()),
                ('Pusit', models.BooleanField()),
                ('Talakitok', models.BooleanField()),
                ('Tanigue', models.BooleanField()),
                ('Tilapia', models.BooleanField()),
                ('Tuna', models.BooleanField()),
                ('Bawang', models.BooleanField()),
                ('Bell pepper', models.BooleanField()),
                ('Carrots', models.BooleanField()),
                ('Kalabasa', models.BooleanField()),
                ('Kalamansi', models.BooleanField()),
                ('Kamatis', models.BooleanField()),
                ('Labanos', models.BooleanField()),
                ('Luya', models.BooleanField()),
                ('Monggo', models.BooleanField()),
                ('Okra', models.BooleanField()),
                ('Patatas', models.BooleanField()),
                ('Petchay Baguio', models.BooleanField()),
                ('Petchay Tagalaog', models.BooleanField()),
                ('Pipino', models.BooleanField()),
                ('Repolyo', models.BooleanField()),
                ('Sayote', models.BooleanField()),
                ('Sibuyas', models.BooleanField()),
                ('Sibuyas Dahon', models.BooleanField()),
                ('Sili anghang', models.BooleanField()),
                ('Sili sigang', models.BooleanField()),
                ('Sitaw', models.BooleanField()),
                ('Talbos Ampalaya', models.BooleanField()),
                ('Talbos Kamote', models.BooleanField()),
                ('Talong', models.BooleanField()),
            ],
        ),
    ]
