# Generated by Django 3.0.8 on 2020-08-12 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_store', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='time_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
