# Generated by Django 3.0.8 on 2020-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0010_auto_20200812_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Alimasag_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Alumahan_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Apple_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Atis_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Bangus_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Bawang_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Bell pepper_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Bisugo_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Carrots_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Galunggong_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Grapes_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Guyabano_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Hipon_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Kalabasa_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Kalamansi_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Kamatis_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Labahita_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Labanos_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Lakatan_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Lemon_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Luya_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Manga_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Monggo_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Okra_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Patatas_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Peras_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Petchay Baguio_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Petchay Tagalaog_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Pipino_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Pusit_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Repolyo_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Saba_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Sayote_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Sibuyas Dahon_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Sibuyas_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Sili anghang_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Sili sigang_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Sitaw_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Talakitok_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Talbos Ampalaya_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Talbos Kamote_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Talong_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Tanigue_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Tilapia_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Tuna_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
