# Generated by Django 3.0.8 on 2020-08-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0011_auto_20200813_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
