# Generated by Django 3.0.8 on 2020-08-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0017_auto_20200813_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['product_category', 'title'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='item_count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='item_thresh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
