# Generated by Django 3.0.8 on 2020-08-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0019_auto_20200813_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Salmon Belly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='Salmon Belly_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
