# Generated by Django 3.0.8 on 2020-08-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0021_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'Requests'},
        ),
    ]
