# Generated by Django 3.0.8 on 2020-08-14 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0022_auto_20200813_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Salmon Belly',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Salmon Belly_counter',
        ),
        migrations.RemoveField(
            model_name='request',
            name='Salmon Belly',
        ),
        migrations.RemoveField(
            model_name='request',
            name='Salmon Belly_counter',
        ),
    ]
