# Generated by Django 3.0.8 on 2020-08-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0023_auto_20200814_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=25)),
                ('my_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='Salmon Belly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='Salmon Belly_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='Salmon Belly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='Salmon Belly_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
