# Generated by Django 3.0.8 on 2020-08-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0024_auto_20200814_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='add_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='add_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
