# Generated by Django 3.1 on 2020-08-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0026_auto_20200814_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Salmon Belly',
            new_name='Ampalaya',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Salmon Belly_counter',
            new_name='Ampalaya_counter',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Talbos Ampalaya',
            new_name='Buto buto',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Talbos Ampalaya_counter',
            new_name='Buto buto_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Salmon Belly',
            new_name='Ampalaya',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Salmon Belly_counter',
            new_name='Ampalaya_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Talbos Ampalaya',
            new_name='Buto buto',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Talbos Ampalaya_counter',
            new_name='Buto buto_counter',
        ),
        migrations.AddField(
            model_name='orders',
            name='Laman Baboy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='Laman Baboy_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Liempo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='Liempo_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Manok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='Manok_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Pata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='Pata_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Salmon Head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='Salmon Head_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Sugpo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='Sugpo_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='Laman Baboy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='Laman Baboy_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='Liempo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='Liempo_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='Manok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='Manok_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='Pata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='Pata_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='Salmon Head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='Salmon Head_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='Sugpo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='Sugpo_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
