# Generated by Django 3.1 on 2020-08-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0027_auto_20200815_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Bell pepper',
            new_name='Bell-pepper',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Bell pepper_counter',
            new_name='Bell-pepper_counter',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Buto buto',
            new_name='Buto-buto',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Buto buto_counter',
            new_name='Buto-buto_counter',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Laman Baboy',
            new_name='Laman-Baboy',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Laman Baboy_counter',
            new_name='Laman-Baboy_counter',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Petchay Baguio',
            new_name='Petchay-Baguio',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Petchay Baguio_counter',
            new_name='Petchay-Baguio_counter',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Salmon Head',
            new_name='Salmon-Head',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Salmon Head_counter',
            new_name='Salmon-Head_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Bell pepper',
            new_name='Bell-pepper',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Bell pepper_counter',
            new_name='Bell-pepper_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Buto buto',
            new_name='Buto-buto',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Buto buto_counter',
            new_name='Buto-buto_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Laman Baboy',
            new_name='Laman-Baboy',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Laman Baboy_counter',
            new_name='Laman-Baboy_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Petchay Baguio',
            new_name='Petchay-Baguio',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Petchay Baguio_counter',
            new_name='Petchay-Baguio_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Salmon Head',
            new_name='Salmon-Head',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Salmon Head_counter',
            new_name='Salmon-Head_counter',
        ),
    ]
