# Generated by Django 3.0.8 on 2020-08-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0028_auto_20200815_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Petchay Tagalaog',
            new_name='Petchay-Tagalaog',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Petchay Tagalaog_counter',
            new_name='Petchay-Tagalaog_counter',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Sibuyas Dahon',
            new_name='Sibuyas-Dahon',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Sibuyas Dahon_counter',
            new_name='Sibuyas-Dahon_counter',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Sili anghang',
            new_name='Sili-anghang',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Sili anghang_counter',
            new_name='Sili-anghang_counter',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Sili sigang',
            new_name='Sili-sigang',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Sili sigang_counter',
            new_name='Sili-sigang_counter',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Talbos Kamote',
            new_name='Talbos-Kamote',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Talbos Kamote_counter',
            new_name='Talbos-Kamote_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Petchay Tagalaog',
            new_name='Petchay-Tagalaog',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Petchay Tagalaog_counter',
            new_name='Petchay-Tagalaog_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Sibuyas Dahon',
            new_name='Sibuyas-Dahon',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Sibuyas Dahon_counter',
            new_name='Sibuyas-Dahon_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Sili anghang',
            new_name='Sili-anghang',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Sili anghang_counter',
            new_name='Sili-anghang_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Sili sigang',
            new_name='Sili-sigang',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Sili sigang_counter',
            new_name='Sili-sigang_counter',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Talbos Kamote',
            new_name='Talbos-Kamote',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Talbos Kamote_counter',
            new_name='Talbos-Kamote_counter',
        ),
    ]
